#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/05b64ab0-d073-476d-b953-a730978e1da5 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float elapsed;
  float rpm;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <SoftwareSerial.h>
SoftwareSerial swSer(D5, D4);

unsigned long time_ms = 0;
// float rpm_eng = 0.0;
// float rpm_gbx = 0.0;
String incomingData = "";


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  swSer.begin(9600);
  WiFi_Start();
  delay(500);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  // IPAddress ip;
  // Serial.println(WiFi.hostByName("google.com", ip));
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void WiFi_Start() {
  WiFi.begin(SSID, PASS);

  Serial.print("Connecting to WiFi");
  while (WiFi.status() != WL_CONNECTED) {
    delay(1000);
    Serial.print(".");
  }

  Serial.println("\nConnected!");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}




void loop() {
  
  
  ArduinoCloud.update();
  
  while (swSer.available()) {
    char c = swSer.read();
    if (c == '\n') {
      parseData(incomingData);
      incomingData = "";
    } else {
      incomingData += c;
    }
  }
}



void parseData(String data) {
  int firstComma = data.indexOf(',');
  int secondComma = data.indexOf(',', firstComma + 1);

  if (firstComma > 0 && secondComma > firstComma) {
    String timeStr = data.substring(0, firstComma);
    String rpmEngStr = data.substring(firstComma + 1, secondComma);
    String rpmGbxStr = data.substring(secondComma + 1);

    time_ms = timeStr.toInt();
    rpm_eng = rpmEngStr.toFloat();
    rpm_gbx = rpmGbxStr.toFloat();

    Serial.print("ActiveTime: "); Serial.print(time_ms);
    Serial.print(" ms, RPM Engine: "); Serial.print(rpm_eng);
    Serial.print(", RPM Gearbox: "); Serial.println(rpm_gbx);
  } else {
    Serial.println("Invalid data format: " + data);
  }
}




